export interface Tool {
  slug: string
  name: string
  shortDescription: string
  seoDescription: string
  h1: string
  category: ToolCategory
  inputFormats: string[]
  outputFormat: string
  icon: string
  featured: boolean
}

export type ToolCategory = 'pdf' | 'image' | 'text' | 'converter'

export const tools: Tool[] = [
  {
    slug: 'merge-pdf',
    name: 'Merge PDF',
    shortDescription: 'Combine multiple PDFs into one file',
    seoDescription: 'Merge multiple PDF files into one instantly. Free, unlimited, no watermarks.',
    h1: 'Merge PDF Files Online — Free, Unlimited',
    category: 'pdf',
    inputFormats: ['PDF'],
    outputFormat: 'PDF',
    icon: 'merge',
    featured: true,
  },
  {
    slug: 'compress-pdf',
    name: 'Compress PDF',
    shortDescription: 'Reduce PDF file size without quality loss',
    seoDescription: 'Compress PDF files online for free. Reduce file size instantly in your browser.',
    h1: 'Compress PDF Online — Free, No Limits',
    category: 'pdf',
    inputFormats: ['PDF'],
    outputFormat: 'PDF',
    icon: 'compress',
    featured: true,
  },
  {
    slug: 'split-pdf',
    name: 'Split PDF',
    shortDescription: 'Extract pages or split into multiple PDFs',
    seoDescription: 'Split PDF files into separate pages or page ranges. Free and unlimited.',
    h1: 'Split PDF Online — Free PDF Splitter',
    category: 'pdf',
    inputFormats: ['PDF'],
    outputFormat: 'PDF',
    icon: 'split',
    featured: false,
  },
  {
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    shortDescription: 'Convert PDF documents to editable Word files',
    seoDescription: 'Convert PDF to Word online free. Get editable .docx files from any PDF.',
    h1: 'PDF to Word Converter — Free Online',
    category: 'converter',
    inputFormats: ['PDF'],
    outputFormat: 'DOCX',
    icon: 'pdf-to-word',
    featured: true,
  },
  {
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    shortDescription: 'Convert Word documents to PDF format',
    seoDescription: 'Convert Word documents to PDF online free. Fast, accurate, no watermarks.',
    h1: 'Word to PDF Converter — Free Online',
    category: 'converter',
    inputFormats: ['DOCX', 'DOC'],
    outputFormat: 'PDF',
    icon: 'word-to-pdf',
    featured: false,
  },
  {
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG',
    shortDescription: 'Convert PDF pages to JPG images',
    seoDescription: 'Convert PDF pages to high-quality JPG images. Free, unlimited, instant.',
    h1: 'PDF to JPG Converter — Free Online',
    category: 'converter',
    inputFormats: ['PDF'],
    outputFormat: 'JPG',
    icon: 'pdf-to-image',
    featured: true,
  },
  {
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    shortDescription: 'Convert JPG images to a PDF document',
    seoDescription: 'Convert JPG images to PDF online free. Combine multiple images into one PDF.',
    h1: 'JPG to PDF Converter — Free Online',
    category: 'converter',
    inputFormats: ['JPG', 'JPEG', 'PNG'],
    outputFormat: 'PDF',
    icon: 'image-to-pdf',
    featured: false,
  },
  {
    slug: 'rotate-pdf',
    name: 'Rotate PDF',
    shortDescription: 'Rotate PDF pages to the correct orientation',
    seoDescription: 'Rotate PDF pages online free. Fix orientation for individual pages or entire document.',
    h1: 'Rotate PDF Online — Free Page Rotator',
    category: 'pdf',
    inputFormats: ['PDF'],
    outputFormat: 'PDF',
    icon: 'rotate',
    featured: false,
  },
  {
    slug: 'unlock-pdf',
    name: 'Unlock PDF',
    shortDescription: 'Remove password protection from PDFs',
    seoDescription: 'Remove PDF password protection online. Unlock encrypted PDFs instantly and free.',
    h1: 'Unlock PDF — Remove Password Protection Free',
    category: 'pdf',
    inputFormats: ['PDF'],
    outputFormat: 'PDF',
    icon: 'unlock',
    featured: false,
  },
  {
    slug: 'protect-pdf',
    name: 'Protect PDF',
    shortDescription: 'Add password protection to your PDF',
    seoDescription: 'Add password protection to PDF files online. Secure your documents instantly, free.',
    h1: 'Protect PDF with Password — Free Online',
    category: 'pdf',
    inputFormats: ['PDF'],
    outputFormat: 'PDF',
    icon: 'lock',
    featured: false,
  },
  {
    slug: 'watermark-pdf',
    name: 'Watermark PDF',
    shortDescription: 'Add a text watermark to your PDF pages',
    seoDescription: 'Add text watermarks to PDF files online free. Customize position, opacity, and style.',
    h1: 'Add Watermark to PDF — Free Online Tool',
    category: 'pdf',
    inputFormats: ['PDF'],
    outputFormat: 'PDF',
    icon: 'watermark',
    featured: false,
  },
  {
    slug: 'compress-image',
    name: 'Compress Image',
    shortDescription: 'Reduce image file size without losing quality',
    seoDescription: 'Compress images online free. Reduce JPG, PNG, WebP file sizes instantly in your browser.',
    h1: 'Image Compressor — Free Online, No Limits',
    category: 'image',
    inputFormats: ['JPG', 'PNG', 'WebP'],
    outputFormat: 'JPG/PNG/WebP',
    icon: 'compress-image',
    featured: true,
  },
  {
    slug: 'resize-image',
    name: 'Resize Image',
    shortDescription: 'Resize images by pixel dimensions or percentage',
    seoDescription: 'Resize images online free. Set exact pixel dimensions or scale by percentage instantly.',
    h1: 'Resize Image Online — Free Image Resizer',
    category: 'image',
    inputFormats: ['JPG', 'PNG', 'WebP', 'GIF'],
    outputFormat: 'JPG/PNG/WebP',
    icon: 'resize',
    featured: true,
  },
  {
    slug: 'convert-image',
    name: 'Convert Image',
    shortDescription: 'Convert between JPG, PNG, WebP, and AVIF',
    seoDescription: 'Convert image formats online free. JPG to PNG, WebP to JPG, and more — instant.',
    h1: 'Image Format Converter — Free Online',
    category: 'image',
    inputFormats: ['JPG', 'PNG', 'WebP', 'AVIF', 'GIF'],
    outputFormat: 'JPG/PNG/WebP/AVIF',
    icon: 'convert',
    featured: false,
  },
  {
    slug: 'crop-image',
    name: 'Crop Image',
    shortDescription: 'Crop images with precision crop handles',
    seoDescription: 'Crop images online free. Drag handles to select the exact crop area instantly.',
    h1: 'Crop Image Online — Free Image Cropper',
    category: 'image',
    inputFormats: ['JPG', 'PNG', 'WebP'],
    outputFormat: 'JPG/PNG',
    icon: 'crop',
    featured: false,
  },
  {
    slug: 'remove-background',
    name: 'Remove Background',
    shortDescription: 'AI-powered background removal from images',
    seoDescription: 'Remove image background online free. AI-powered, instant results with transparent PNG output.',
    h1: 'Remove Background from Image — Free AI Tool',
    category: 'image',
    inputFormats: ['JPG', 'PNG'],
    outputFormat: 'PNG',
    icon: 'remove-bg',
    featured: true,
  },
  {
    slug: 'word-count',
    name: 'Word Count',
    shortDescription: 'Count words, characters, sentences, and more',
    seoDescription: 'Free online word counter. Count words, characters, sentences, paragraphs, and reading time.',
    h1: 'Word Count Tool — Free Online Word Counter',
    category: 'text',
    inputFormats: ['TXT'],
    outputFormat: 'Stats',
    icon: 'word-count',
    featured: true,
  },
  {
    slug: 'case-converter',
    name: 'Case Converter',
    shortDescription: 'Convert text to UPPER, lower, Title, or camelCase',
    seoDescription: 'Convert text case online free. UPPER, lower, Title Case, Sentence case, camelCase instantly.',
    h1: 'Text Case Converter — Free Online Tool',
    category: 'text',
    inputFormats: ['TXT'],
    outputFormat: 'TXT',
    icon: 'case',
    featured: false,
  },
  {
    slug: 'remove-duplicate-lines',
    name: 'Remove Duplicate Lines',
    shortDescription: 'Remove duplicate lines from any text',
    seoDescription: 'Remove duplicate lines from text online free. Clean up lists and text files instantly.',
    h1: 'Remove Duplicate Lines — Free Online Tool',
    category: 'text',
    inputFormats: ['TXT'],
    outputFormat: 'TXT',
    icon: 'dedup',
    featured: false,
  },
  {
    slug: 'diff-checker',
    name: 'Diff Checker',
    shortDescription: 'Compare two texts and highlight differences',
    seoDescription: 'Compare text online free. Side-by-side diff checker with highlighted changes instantly.',
    h1: 'Text Diff Checker — Compare Text Online Free',
    category: 'text',
    inputFormats: ['TXT'],
    outputFormat: 'Diff',
    icon: 'diff',
    featured: false,
  },
  {
    slug: 'url-encoder',
    name: 'URL Encoder',
    shortDescription: 'Encode and decode URLs and URL components',
    seoDescription: 'URL encode and decode online free. Encode special characters for use in URLs instantly.',
    h1: 'URL Encoder / Decoder — Free Online Tool',
    category: 'text',
    inputFormats: ['TXT'],
    outputFormat: 'TXT',
    icon: 'url',
    featured: false,
  },
  {
    slug: 'base64',
    name: 'Base64 Encoder',
    shortDescription: 'Encode and decode Base64 strings',
    seoDescription: 'Base64 encode and decode online free. Convert text and files to Base64 format instantly.',
    h1: 'Base64 Encoder / Decoder — Free Online Tool',
    category: 'text',
    inputFormats: ['TXT'],
    outputFormat: 'TXT',
    icon: 'base64',
    featured: false,
  },
]

export const toolsByCategory = (category: ToolCategory) =>
  tools.filter((t) => t.category === category)

export const featuredTools = tools.filter((t) => t.featured)

export const categoryLabels: Record<ToolCategory, string> = {
  pdf: 'PDF Tools',
  image: 'Image Tools',
  text: 'Text Tools',
  converter: 'Converter Tools',
}
